@host = https://thebrotherstoys--focus-infusion-463923-t8.us-east4.hosted.app
### GET  List all products
{{host}}/products

### GET a product by ID
{{host}}/products/0bIMcrwWKjbOVnJkEkTP


### POST  Create a new product
POST {{host}}/products
Content-Type: application/json

{
  "name": "Conor McGregor Action Figure",
  "price": 390.00,
  "description": "Conor McGregor Action Figure",
  "images": ["https://example.com/image1.jpg"],
  "tags": ["McFarlane", "UFC"]
}

### PUT  Update a new product
PUT {{host}}/products/09da0f28-1e64-481b-b35a-d67564b5101f
Content-Type: application/json

{
  "name": "Conor McGregor",
  "price": 375.00
}