@host = https://thebrotherstoys--focus-infusion-463923-t8.us-east4.hosted.app/
### GET  List all products
{{host}}/api/products

### GET a product by ID
{{host}}/api/products/0bIMcrwWKjbOVnJkEkTP


### POST  Create a new product
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "SCARFACE",
  "price": 390.00,
  "description": "Tony Montana Action Figure",
  "imageUrl": ["https://example.com/image1.jpg"],
  "tags": ["McFarlane", "Movies"]
}

### PUT  Update a new product
PUT {{host}}/products/bbf188f8-a88c-4d4c-a652-37e233763d38
Content-Type: application/json

{
  "price": 360.00
}

### DELETE a product by ID
DELETE {{host}}/products/0bIMcrwWKjbOVnJkEkTP
